### ISSUE TITLE
Error with new oauth

### ISSUE THREAD

**Issue by APraxx** [johnwarne/reddit-top-rss#19]
Thanks for improving this app.

I provided my docker the credentials for the new app via env
It seems to work but outputs this error.

```
 [11-May-2023 09:36:42] NOTICE: fpm is running, pid 9
 [11-May-2023 09:36:42] NOTICE: ready to handle connections
 NOTICE: PHP message: PHP Warning:  include(auth.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 11
 NOTICE: PHP message: PHP Warning:  include(): Failed opening 'auth.php' for inclusion (include_path='.:/usr/share/php8') in /var/www/html/index.php on line 11
 2023/05/11 09:36:52 [error] 12#12: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  include(auth.php): Failed to open stream: No such file or directory in /var/www/html/index.php on line 11PHP message: PHP Warning:  include(): Failed opening 'auth.php' for inclusion (include_path='.:/usr/share/php8') in /var/www/html/index.php on line 11" while reading response header from upstream, client: 192.168.16.28, server: _, request: "GET /?subreddit=worldnews&averagePostsPerDay=4 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "reddit-top-rss.mysite.org"
 NOTICE: PHP message: PHP Warning:  include(auth.php): Failed to open stream: No such file or directory in /var/www/html/postlist.php on line 11
 NOTICE: PHP message: PHP Warning:  include(): Failed opening 'auth.php' for inclusion (include_path='.:/usr/share/php8') in /var/www/html/postlist.php on line 11
 NOTICE: PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 23
 NOTICE: PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 26
 NOTICE: PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 32
 NOTICE: PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 41
 NOTICE: PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/postlist.php on line 41
 2023/05/11 09:36:54 [error] 12#12: *3 FastCGI sent in stderr: "PHP message: PHP Warning:  include(auth.php): Failed to open stream: No such file or directory in /var/www/html/postlist.php on line 11PHP message: PHP Warning:  include(): Failed opening 'auth.php' for inclusion (include_path='.:/usr/share/php8') in /var/www/html/postlist.php on line 11PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 23PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 26PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 32PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/sort-and-filter.php on line 41PHP message: PHP Warning:  Undefined variable $accessToken in /var/www/html/postlist.php on line 41" while reading response header from upstream, client: 192.168.16.28, server: _, request: "GET /postlist.php?subreddit=worldnews&score=&threshold=&averagePostsPerDay=4 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "reddit-top-rss.mysite.org", referrer: "https://reddit-top-rss.mysite.org/?subreddit=worldnews&averagePostsPerDay=4"
``` 

its a new container and manually built as per the git master dockerfile

edit: checked your dockerhub image same thing

**Comment by johnwarne** [comment]
Thanks for testing! I just pushed up a fix to include the necessary changes to the Dockerfile (and a new `lastest` container). Can you test again?

**Comment by APraxx** [comment]
DISCLAIMER seems to be on my side because of long response times

so did some testing

had an error but not sure if this isn't a problem on my side because i only saw it once
```
 [11-May-2023 13:07:13] NOTICE: fpm is running, pid 9
 [11-May-2023 13:07:13] NOTICE: ready to handle connections
 NOTICE: PHP message: PHP Warning:  Attempt to read property "access_token" on null in /var/www/html/auth.php on line 38
 2023/05/11 13:07:27 [error] 10#10: *1 FastCGI sent in stderr: "PHP message: PHP Warning:  Attempt to read property "access_token" on null in /var/www/html/auth.php on line 38" while reading response header from upstream, client: 192.168.16.28, server: _, request: "GET /?subreddit=worldnews&averagePostsPerDay=4 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "reddit-top-rss.mysite.org"
 2023/05/11 13:08:13 [error] 10#10: *11 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 192.168.16.28, server: _, request: "GET /favicon.ico HTTP/1.1", host: "reddit-top-rss.mysite.org", referrer: "https://reddit-top-rss.mysite.org/?subreddit=worldnews&averagePostsPerDay=4&view=rss"
 [11-May-2023 13:08:54] NOTICE: Terminating ...
 [11-May-2023 13:08:54] NOTICE: exiting, bye-bye!
``` 

```
 [11-May-2023 13:08:56] NOTICE: fpm is running, pid 8
 [11-May-2023 13:08:56] NOTICE: ready to handle connections
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56
 NOTICE: PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56
 NOTICE: PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/html/sort-and-filter.php:56
 Stack trace:
 #0 /var/www/html/postlist.php(15): include()
 #1 {main}
   thrown in /var/www/html/sort-and-filter.php on line 56
 2023/05/11 13:11:37 [error] 9#9: *37 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/html/sort-and-filter.php:56
 Stack trace:
 #0 /var/www/html/postlist.php(15): include()
 #1 {main}
   thrown in /var/www/html/sort-and-filter.php on line 56" while reading response header from upstream, client: 192.168.16.28, server: _, request: "GET /postlist.php?subreddit=worldnews&score=&threshold=15000&averagePostsPerDay= HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "reddit-top-rss.mysite.org", referrer: "https://reddit-top-rss.mysite.org/?subreddit=worldnews&threshold=15000"

``` 

edit: it seems my connection where i am currently isn't that good . i'll try again when i can rule out it's not because of timeouts and long response times on my side.

**Comment by APraxx** [comment]
Everything seems to run nice.

Does an rss endpoint have a favicon? ;)
```
2023/05/11 14:27:25 [error] 10#10: *317 open() "/var/www/html/favicon.ico" failed (2: No such file or directory), client: 192.168.16.28, server: _, request: "GET /favicon.ico HTTP/1.1", host: "reddit-top-rss.mysite.org", referrer: "https://reddit-top-rss.mysite.org/?subreddit=worldnews&averagePostsPerDay=5&view=rss"
```
