### ISSUE TITLE
Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56

### ISSUE THREAD

**Issue by markus1189** [johnwarne/reddit-top-rss#20]
I am running `reddit-top-rss` as a local docker container.  A couple days ago, it stopped working and now feeds showed up in my RSS reader.

I read about the authorization using the client_id and client_secret and added that to my container as described in the README.

However, it does still not work.

The `docker logs` show the following:

```
172.17.0.1 - - [06/Jun/2023:06:12:39 +0000] "GET /?subreddit=fantasy&threshold=50&view=rss HTTP/1.1" 500 5 "-" "Newsboat/2.31.0 (Linux x86_64)" "-" 0.393 0.393 . -
2023/06/06 06:12:39 [error] 9#9: *13170 FastCGI sent in stderr: "PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56PHP message: PHP Warning:  Trying to access array offset on value of type null in /var/www/html/sort-and-filter.php on line 56PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($var) must be of type Countable|array, null given in /var/www/html/sort-and-filter.php:56
Stack trace:
#0 /var/www/html/rss.php(17): include()
#1 /var/www/html/index.php(25): include('...')
#2 {main}
  thrown in /var/www/html/sort-and-filter.php on line 56" while reading response header from upstream, client: 172.17.0.1, server: _, request: "GET /?subreddit=fantasy&threshold=50&view=rss HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "localhost:9999"
```

Visiting the website shows this:

![image](https://github.com/johnwarne/reddit-top-rss/assets/591567/40d38f4e-e07f-47df-818f-ca0425033c10)

Did I do something wrong with the credentials, or has reddit-to-rss stopped working?

**Comment by markus1189** [comment]
Weird, I though I had pulled the most recent image locally, but I assume there was some caching going on.

After removing the image and pulling `latest` again it seems to work :heart: 

Switched to using an explicit 1.2 tag to avoid this next time
